server:
  port: 8090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tes?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

# mybatis设置
mybatis:
  type-aliases-package: com.csmaxwell.tes.domain
  mapper-locations: classpath:com.csmaxwell.tes.dao/*.xml

# pageHelper设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

# 设置日志级别
logging:
  level:
    com.csmaxwell.tes: debug
    org.springframework: info

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Apple  #JWT负载中拿到开头
