server:
  port: 8090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tes
    username: root
    password: 599890897

# mybatis设置
mybatis:
  type-aliases-package: com.csmaxwell.tes.domain
  mapper-locations: classpath:com.csmaxwell.tes.dao/*.xml

# pageHelper设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

# 设置日志级别
logging:
  level:
    com.csmaxwell.tes: debug
    org.springframework: info

